# Render.com Blueprint Configuration
# Docs: https://render.com/docs/blueprint-spec
services:
  - type: web
    name: cineverse-bot
    env: docker
    dockerfilePath: Dockerfile
    region: oregon
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DB_CHANNEL_ID
        sync: false
      - key: OWNER_ID
        value: 7831101047
      - key: ADMIN_ID
        sync: false
      - key: FSUB_GROUP_ID
        value: -1004427640174
      - key: FSUB_GROUP_LINK
        value: https://t.me/CineVerseFlimSearch
      - key: CHANNEL_LINK
        value: https://t.me/CineVerseFlimSearch
      - key: DEVELOPER_LINK
        sync: false
